// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMA-8kMRPPc4tD3sKvpPJrbt2OoFLkm-s',
    appId: '1:672847406453:web:89884b801d555da18c1f3c',
    messagingSenderId: '672847406453',
    projectId: 'weather-app-graphe',
    authDomain: 'weather-app-graphe.firebaseapp.com',
    storageBucket: 'weather-app-graphe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr2Eg7LOwIgqyMqqsC4oU3P4Q7DK1cGlw',
    appId: '1:672847406453:android:03cd9330346fdf588c1f3c',
    messagingSenderId: '672847406453',
    projectId: 'weather-app-graphe',
    storageBucket: 'weather-app-graphe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZfmusWlYMY6AvU_7wh1p5Qv9uGbfb0GE',
    appId: '1:672847406453:ios:ad600d9ad80c178f8c1f3c',
    messagingSenderId: '672847406453',
    projectId: 'weather-app-graphe',
    storageBucket: 'weather-app-graphe.appspot.com',
    iosBundleId: 'com.example.graphedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZfmusWlYMY6AvU_7wh1p5Qv9uGbfb0GE',
    appId: '1:672847406453:ios:601c219628301fed8c1f3c',
    messagingSenderId: '672847406453',
    projectId: 'weather-app-graphe',
    storageBucket: 'weather-app-graphe.appspot.com',
    iosBundleId: 'com.example.graphedemo.RunnerTests',
  );
}
